name: howdy
description: A pleasant Dart CLI library.
version: 0.0.3
repository: https://github.com/ericwindmill/howdy

environment:
  sdk: ^3.12.0-113.1.beta

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  path: ^1.9.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
